name: Build with devenv
on:
  schedule:
    - cron: '21 18 * * 5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-20.04, macos-latest]
        fail-fast: false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set DEVENV_WORKSPACE
      run: echo "DEVENV_WORKSPACE=${GITHUB_WORKSPACE}/devenv" >> $GITHUB_ENV
    - name: Dependency (devenv)
      run: |
        git clone https://github.com/solvcon/devenv.git
    - name: Configure SSH
      if: matrix.os == 'disable'
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-setup-ssh.sh
    - name: Dependency (Ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-setup-apt.sh
    - name: Launch SOLVCON
      run: |
        source ${DEVENV_WORKSPACE}/scripts/init
        devenv add prime
        devenv use prime
        devenv show
        devenv launch solvcon
    - name: Show Dependency
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-show-dep.sh
    - name: Show Python Env
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-show-python-env.sh
    - name: SOLVCON Function Test From Package
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-solvcon-function-test.sh
